source:
  id: copernicus_clms_forest
  provider: copernicus
  product: clms_forest
  product_group: land_cover
  version: "2021"
  description: "Copernicus Land Monitoring Service High Resolution Layer Forest products: Tree Cover Density and Dominant Leaf Type"
  page_url: "https://land.copernicus.eu/en/products/high-resolution-layer-forests-and-tree-cover"
  source_crs: EPSG:3035
  source_period: "2021"
  citation: "Copernicus Land Monitoring Service. High Resolution Layer Forests and Tree Cover."

dataset:
  layer_structure: static_multi
  file_format: geotiff
  native_resolution_m: 10
  data_type: mixed

domains:
  clip_aoi_config: configs/aoi/pyrenees_full.yaml
  output_aoi_config: configs/aoi/experimental_pallars_sobira.yaml

download:
  enabled: true
  mode: wekeo_hda
  overwrite_existing: false

  hda:
    max_workers: 2
    max_results: 50
    temporary_dir: data_raw/copernicus/_hda_downloads
    move_downloaded_to_raw: false
    mosaic_compression: LZW
    sleep_after_download_seconds: 2

  files:
    tree_cover_density:
      filename: tree_cover_density_2021_10m_pyrenees_full_mosaic.tif
      max_results: 50
      file_pattern: "*.zip"
      zip_member_pattern: ".*\\.tif$"
      postprocess: mosaic_zip_geotiff
      hda_query:
        dataset_id: "EO:EEA:DAT:HRL:TCF"
        bbox:
          - -2.28618323
          - 41.9550235
          - 3.18030846
          - 43.47467682
        productType: "Tree Cover Density"
        resolution: "10m"
        year: "2021"
        itemsPerPage: 200
        startIndex: 0

    dominant_leaf_type:
      filename: dominant_leaf_type_2021_10m_pyrenees_full_mosaic.tif
      max_results: 50
      file_pattern: "*.zip"
      zip_member_pattern: ".*\\.tif$"
      postprocess: mosaic_zip_geotiff
      hda_query:
        dataset_id: "EO:EEA:DAT:HRL:TCF"
        bbox:
          - -2.28618323
          - 41.9550235
          - 3.18030846
          - 43.47467682
        productType: "Dominant Leaf Type"
        resolution: "10m"
        year: "2021"
        itemsPerPage: 200
        startIndex: 0

processing:
  source_resolution: 10m
  target_resolution_m: 100
  grid_from_project: true

resampling:
  default: nearest
  by_variable:
    tree_cover_density: average
    dominant_leaf_type: nearest

variables:
  tree_cover_density:
    enabled: true
    description: "Tree Cover Density"
    unit: percent
    scale_factor: 1.0
    valid_range: [0, 100]
    data_type: percentage
    native_resolution_m: 10
    temporal:
      type: static
      reference_year: 2021

  dominant_leaf_type:
    enabled: true
    description: "Dominant Leaf Type"
    unit: class
    scale_factor: 1.0
    valid_range: [0, 255]
    data_type: categorical
    native_resolution_m: 10
    round_values: true
    temporal:
      type: static
      reference_year: 2021

output:
  write_geotiff: true
  write_sidecar_json: true
  compression: LZW
  dtype: float32

validation:
  fail_on_out_of_range: false
  max_out_of_range_fraction: 0.001