source:
  id: worldclim_cruts4_09_monthly
  provider: worldclim
  product: cruts4_09_monthly
  product_group: historical_monthly_weather
  version: "CRU-TS-4.09"
  description: "WorldClim historical monthly weather data, 1950-2024"
  base_url: "https://geodata.ucdavis.edu/climate/worldclim/2_1/hist/cts4.09"
  page_url: "https://www.worldclim.org/data/monthlywth.html"
  source_crs: EPSG:4326
  source_period: "1950-2024"
  citation: "WorldClim historical monthly weather data downscaled from CRU-TS-4.09 by the Climatic Research Unit, University of East Anglia, using WorldClim 2.1 for bias correction. Cite Harris et al. 2020 for CRU-TS and Fick & Hijmans 2017 for WorldClim 2."

dataset:
  layer_structure: monthly_time_series
  file_format: zip_geotiff
  temporal_axis: year_month
  zip_variable_mode: variable_period
  zip_file_pattern: "wc2.1_cruts4.09_{resolution}_{variable}_{period}.zip"
  tif_file_pattern: "wc2.1_cruts4.09_{resolution}_{variable}_{year}-{month:02d}.tif"

domains:
  clip_aoi_config: configs/aoi/pyrenees_full.yaml
  output_aoi_config: configs/aoi/experimental_pallars_sobira.yaml

download:
  enabled: true
  mode: auto
  overwrite_existing: false
  keep_global_zip_after_clip: false

processing:
  source_resolution: 10m
  target_resolution_m: 100

resampling:
  default: nearest


periods:
  - "1950-1959"
  - "1960-1969"
  - "1970-1979"
  - "1980-1989"
  - "1990-1999"
  - "2000-2009"
  - "2010-2019"
  - "2020-2024"

variables:
  tmin:
    enabled: true
    unit: degC
    scale_factor: 0.1
  tmax:
    enabled: true
    unit: degC
    scale_factor: 0.1
  prec:
    enabled: true
    unit: mm
    scale_factor: 1.0

temporal_aggregations:
  - name: annual_mean_temperature_1991_2020
    years: [1991, 2020]
    months: [1, 12]
    metric: mean
    variables: [tmin, tmax]

  - name: may_sep_mean_temperature_1991_2020
    years: [1991, 2020]
    months: [5, 9]
    metric: mean
    variables: [tmin, tmax]

  - name: mean_annual_precipitation_1991_2020
    years: [1991, 2020]
    months: [1, 12]
    within_year_metric: sum
    across_year_metric: mean
    output_metric_name: mean_annual_sum
    variables: [prec]

  - name: mean_may_sep_precipitation_1991_2020
    years: [1991, 2020]
    months: [5, 9]
    within_year_metric: sum
    across_year_metric: mean
    output_metric_name: mean_period_sum
    variables: [prec]

output:
  write_geotiff: true
  write_sidecar_json: true
  compression: LZW
  dtype: float32

validation:
  fail_on_out_of_range: false
  max_out_of_range_fraction: 0.001